# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "InstaGrade Scanner" do

pod "OpenCV"
pod "GPUImage"
pod "msgpack"
pod "CargoBay"
pod "KSReachability"
pod "PBWebViewController"

end

target "ScantronKitTests" do

end

